# Generated by Django 3.1.2 on 2020-10-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='path',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
