# Generated by Django 3.1.2 on 2021-01-28 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201101_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_path',
            field=models.CharField(default=None, max_length=415),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
