# Generated by Django 3.1.2 on 2021-01-30 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210128_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_path',
            field=models.CharField(max_length=415),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
