# Generated by Django 3.1.2 on 2021-03-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210211_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, upload_to='storage'),
            preserve_default=False,
        ),
    ]
