# Generated by Django 3.1.2 on 2021-03-15 08:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=api.models.upload_folder_path),
        ),
    ]
