# Generated by Django 3.1.2 on 2021-05-27 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210315_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='api.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
